# Generated by Django 5.2.4 on 2025-07-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdyapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_type', models.CharField(choices=[('rooster', 'Rooster'), ('hen', 'Hen'), ('chick', 'Chick')], max_length=10)),
                ('niram', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2)),
                ('age', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video', models.FileField(blank=True, null=True, upload_to='bird_videos/')),
                ('father_image', models.ImageField(upload_to='bird_images/')),
                ('father_video', models.FileField(blank=True, null=True, upload_to='bird_videos/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdyapp.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
