# Generated by Django 5.2.4 on 2025-07-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdyapp', '0004_birdproduct_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirdProduct',
        ),
    ]
