# Generated by Django 5.2.4 on 2025-07-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdyapp', '0007_alter_birdproduct_age_alter_birdproduct_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdproduct',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
