# Generated by Django 5.2.4 on 2025-07-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdyapp', '0009_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
