# Generated by Django 5.2.4 on 2025-07-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdyapp', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
